spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:nrj-ft?MODE=MYSQL&DB_CLOSE_DELAY=-1&DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 60000
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size : 100
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true


